# -*- coding: utf-8 -*-
"""Emailspamdetectiontask4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdeXnoam8dx-xzG1ilXqZMurH2y5adXm

**NAME:UMA GANGA VAISHNAVI POTTURI**

IMPORTING NECESSARY LIBRARIES
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

"""**OBTAINING THE DATA**"""

data=pd.read_csv("/content/spam.csv",encoding='latin1')#reading the data

data

"""**ANALYSING THE DATA**"""

data=data.where((pd.notnull(data)))

data.head() #returns first 5 rows of the data

data.shape

data.size

data.describe()

"""**DATA PREPROCESSING**"""

data.drop(columns=["Unnamed: 2","Unnamed: 3", "Unnamed: 4"], inplace=True)

data

data.info()

data=data.rename(columns={'v1':'Target','v2':'Message'})#renaming the columns

data.loc[data['Target']=='spam', 'Target']=1#replacing the target values
data.loc[data['Target']=='ham', 'Target']=0

x=data['Message']
y=data['Target']

x

y

data.head()

"""**Train Test Split**"""

x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=3)

x_train=x_train.astype(str)
y_train=y_train.astype(int)
x_test=x_test.astype(str)
y_test=y_test.astype(int)

x_train.shape

y_train.shape

cv=CountVectorizer()

x_train_cv =cv.fit_transform(x_train)

x_test_cv =cv.transform(x_test)

print(x_train_cv)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

lr.fit(x_train_cv,y_train)

y_pred=lr.predict(x_test_cv)

"""**Accuracy Score**"""

print(accuracy_score(y_test, y_pred)*100)